In [1]:
import numpy as np

In [2]:
n = np.arange(27)

In [3]:
type(n)

numpy.ndarray

In [4]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [2]:
!ls

geocoding_exercise.ipynb
grey_image.png
numpy_handson.ipynb
pandas_lab1.ipynb
supermarkets-commas.txt
supermarkets-commas_without_headers.txt
supermarkets-semi-colons.txt
supermarkets.csv
supermarkets.json
supermarkets.xlsx


In [2]:
import cv2

In [3]:
# read image as grey image
im_g = cv2.imread('grey_image.png', 0)
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [4]:
# read image as color image
im_c = cv2.imread('grey_image.png', 1)
print(im_c)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [5]:
cv2.imwrite("new_grey_image.png", im_g)

True

In [4]:
im_g[1:3,1:3]

array([[125, 255],
       [134, 255]], dtype=uint8)

In [5]:
im_g[:,:3]

array([[187, 158, 104],
       [198, 125, 255],
       [209, 134, 255]], dtype=uint8)

In [6]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [7]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [8]:
ims = np.hstack((im_g,im_g,im_g))
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [9]:
ims = np.vstack((im_g,im_g,im_g))
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [10]:
hs = np.hsplit(ims,5)
print(hs)

[array([[187],
       [198],
       [209],
       [187],
       [198],
       [209],
       [187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134],
       [158],
       [125],
       [134],
       [158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255],
       [104],
       [255],
       [255],
       [104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182],
       [143],
       [147],
       [182],
       [143],
       [147],
       [182]], dtype=uint8)]


In [12]:
vs = np.vsplit(ims,3)
print(vs)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]
